
const args = process.argv.slice(2);

console.log('args--->', args);
const [base_branch, head_branch, gh_token = ''] = args;

// create-pr.js
const createAndMergePR = async () => {
  const { Octokit } = await import('@octokit/rest');

  const octokit = new Octokit({
    auth: gh_token
  });

  try {
    const response = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
      owner: 'ThyeeZz',
      repo: 'action-test',
      title: 'Automated updates',
      body: 'Auto-generated by GitHub Actions',
      head: `ThyeeZz:${head_branch}`,
      base: base_branch
    });

    const pullNumber = response.data.number;
    console.log('PR created:', pullNumber);

    const mergeResponse = await octokit.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge', {
      owner: 'ThyeeZz',
      repo: 'action-test',
      pull_number: pullNumber,
      commit_title: 'Automated i18n updates',
      commit_message: 'sync i18n' + new Date()
    });
    console.log('pr merge result:', mergeResponse.data.message);

  } catch (error) {
    console.error('Error creating PR:', error);
    process.exit(1);
  }
};

createAndMergePR();
