
const args = process.argv.slice(2);

console.log('args--->', args)
const [base_branch, head_branch, gh_token = ''] = args


// create-pr.js
const createPR = async () => {
  const { Octokit } = await import('@octokit/rest');
  
  const octokit = new Octokit({
    auth:  gh_token
  });

  try {
    const response = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
      owner: 'ThyeeZz',
      repo: 'action-test',
      title: 'Automated updates',
      body: 'Auto-generated by GitHub Actions',
      head: `ThyeeZz:${head_branch}`,
      base: base_branch
    });
    console.log('PR created:', response.data.html_url);
  } catch (error) {
    console.error('Error creating PR:', error);
    process.exit(1);
  }
};

createPR();
