name: i18n-translation-sync

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs: 
  sync-translations:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: $GITHUB_REF_NAME
      WORK_BRANCH: auto-update-$(date +%Y%m%d-%H%M)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create and switch to new branch
        run: |
          git fetch origin ${{ env.BASE_BRANCH }}
          git checkout -b ${{ env.WORK_BRANCH }} origin/${{ env.BASE_BRANCH }}
          echo "Base branch: ${{ env.BASE_BRANCH }}"
          echo "Work branch: ${{ env.WORK_BRANCH }}"
          
      - name: Make changes
        run: |
          node ./scripts/create-pr.js
          git config --global user.email "jialian.ji@zilliz.com"
          git config --global user.name "ThyeeZz"
          git add .
          git commit -m "Automated updates"
          git push --set-upstream origin ${{ env.WORK_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            
      - name: Create Pull Request
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Base branch: ${{ env.BASE_BRANCH }}"
          echo "Head branch: ${{ env.WORK_BRANCH }}"
          
          # 等待几秒确保分支已经创建
          sleep 5
          
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/ThyeeZz/action-test/pulls" \
            -d '{
              "title": "Automated updates",
              "body": "Auto-generated by GitHub Actions",
              "head": "ThyeeZz:${{ env.WORK_BRANCH }}",
              "base": "${{ env.BASE_BRANCH }}"
            }'

      - name: Auto-Merge PR
        if: success()
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$(jq -r '.number' $GITHUB_EVENT_PATH)/merge" \
            -d '{"merge_method": "squash"}'
